### ISSUE TITLE
Can't use `Timex.Date.shift/2` to generate a module attribute value

### ISSUE THREAD

**Issue by myronmarston** [bitwalker/timex#159]
### Steps to reproduce

We've been using Timex 0.19.2 for awhile and decided to try and upgrade to the latest.  When compiling, I get an error:

```
== Compilation error on file test/support/time_slice_helpers.ex ==
** (ArgumentError) argument error
    (stdlib) :ets.lookup(:tzdata_current_release, :release_version)
    lib/tzdata/release_reader.ex:41: Tzdata.ReleaseReader.current_release_from_table/0
    lib/tzdata/release_reader.ex:13: Tzdata.ReleaseReader.simple_lookup/1
    lib/tzdata/release_reader.ex:7: Tzdata.ReleaseReader.zone_and_link_list/0
    lib/tzdata.ex:61: Tzdata.zone_exists?/1
    lib/timezone/timezone.ex:166: Timex.Timezone.do_get/3
    lib/timezone/timezone.ex:310: Timex.Timezone.convert/2
    lib/datetime/datetime.ex:532: Timex.DateTime.to_seconds/3
```

Looking at the `test/support/time_slice_helpers.ex`, I found the problem:

``` elixir
@traffic_dates Date.dates_in_range("2015-01-01", "2016-02-29", :days) |> Enum.to_list
```

This `@traffic_dates` module attribute is essentially a constant that is used in multiple functions in this module.  `Date` here is one of our modules, and if I replace the module attribute with `[]` it compiles fine --- so this line is clearly causing the compile error.  I boiled it down to an expression that uses only `Timex.Date` functions and I got something that fails in the same way:

``` elixir
@date_1 Timex.Date.from({2016, 1, 1}) |> Timex.Date.shift(days: 31)
```

### Description of issue

It looks like `Timex.Date.shift/2` requires an ETS table to work but the table isn't available at compile time so we can't use it to generate a value for a module attribute like we could in Timex 0.19.2.

**Comment by craigbeck** [comment]
Found I had a similar issue with an `:ets.lookup` call and followed it to the `tzdata` package needing to be started -- see [Getting Started](https://github.com/lau/tzdata#getting-started) section of the [tzdata](https://github.com/lau/tzdata) repo. 

After I added `:tzdata` to the list of `applications` to be started in my `mix.exs` file the issue was resolved.

without starting `tzdata`:

```
iex(1)> Timex.DateTime.from_timestamp(:os.timestamp)
** (ArgumentError) argument error
    (stdlib) :ets.lookup(:tzdata_current_release, :release_version)
             lib/tzdata/release_reader.ex:41: Tzdata.ReleaseReader.current_release_from_table/0
             lib/tzdata/release_reader.ex:13: Tzdata.ReleaseReader.simple_lookup/1
             lib/tzdata/release_reader.ex:7: Tzdata.ReleaseReader.zone_and_link_list/0
             lib/tzdata.ex:61: Tzdata.zone_exists?/1
             lib/timezone/timezone.ex:166: Timex.Timezone.do_get/3
             lib/timezone/timezone.ex:310: Timex.Timezone.convert/2
             lib/datetime/datetime.ex:532: Timex.DateTime.to_seconds/3
             lib/datetime/datetime.ex:436: Timex.DateTime.from_microseconds/2
```

after adding `tzdata` to `applications`:

```
iex(1)> Timex.DateTime.from_timestamp(:os.timestamp)
#<DateTime(2016-05-10T00:40:47Z)>
```

**Comment by bitwalker** [comment]
More specifically you need to add Timex to `applications`, as Timex already has `tzdata` in it's applications list, but either one works.

**Comment by craigbeck** [comment]
Thx!

-- 
Craig Beck


On May 20, 2016 at 3:43:21 PM, Paul Schoenfelder (notifications@github.com) wrote:

More specifically you need to add Timex to applications, as Timex already has tzdata in it's applications list, but either one works.

**Comment by myronmarston** [comment]
@bitwalker we have `timex` in our list of applications and were still getting the compile-time error I mentioned above.  Would you expect these functions to work at compile time?

**Comment by bitwalker** [comment]
No, you'd need to start `tzdata` using `Application.ensure_all_started(:tzdata)` prior to where you define the module attribute - putting applications in the applications list is only relevant at runtime, not compile time.
